### ISSUE TITLE
EF Core Plans

### ISSUE THREAD

**Issue by ardalis** [moozzyk/EFCache#12]
Any plans to support EF Core? I read through the README and your blog post and didn't see any plans there, so sorry if it's posted somewhere.

**Comment by moozzyk** [comment]
There are no plans to support EF Core. Given how tightly EFCache is coupled to the provider model and how EF6 works it would mean a complete rewrite. Since I left the EF team I have not looked into how EF Core works internally but it is likely that caching needs to be implemented differently (i.e. not as a wrapping provider) and, as a result, can work better (i.e. on the entity level instead of RecordSet level)
