### ISSUE TITLE
Missing ConfigureAwait(false) leads to potential deadlocks when running under SychronizationContext

### ISSUE THREAD

**Issue by pjhuck** [moozzyk/EFCache#38]
[CachingCommand](https://github.com/moozzyk/EFCache/blob/master/EFCache/CachingCommand.cs#L217) uses the `await` operator, but never calls `ConfigureAwait(false)`. This can lead to deadlocks when running under certain SynchronizationContexts, such as asp.net. As a best practice, all "library code" should always use `ConfigureAwait(false)` on all awaited calls. Here's some reading on the topic:

https://blogs.msdn.microsoft.com/alazarev/2017/05/20/fun-with-configureawait-and-deadlocks-in-asp-net/
https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html
https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

Happy to submit a PR with these changes.

**Comment by moozzyk** [comment]
Thanks for bringing this up. I wonder if this is a real problem or a hypothetical scenario. Were you actually able to hit a deadlock caused by this? Can you share a repro?
My thinking is that EFCache sits between EF and the database so if `ConfigureAwait` needs to be introduced it should be at the EF level since this is the library that invokes these methods.

**Comment by pjhuck** [comment]
Yes, It is a real problem that we've run into. EF internally makes sure not to continue on the captured context,. They actually wrote their own awaitable that does flow the CurrentCulture, but not the synchronization context. You can see that in this commit: https://github.com/aspnet/EntityFramework6/commit/2ec5bf6c79a389c87a718acba5eb50a79e0c9a32  
However, it is not enough for EF to do it, the EFCache has to do it as well. 

Below is a sample web app which reproduces the issue. You will need to create a Sql Server database with this [seed script](https://github.com/pjhuck/EFCache/blob/deadlock/SampleWeb/createdb.sql), and then hit /home/deadlock to deadlock the app. You can also hit /home/nodeadlock to see how avoiding the synchronization context solves the problem.  The controller endpoint is here: https://github.com/pjhuck/EFCache/blob/deadlock/SampleWeb/Controllers/HomeController.cs#L23

Her'es the whole project:
https://github.com/pjhuck/EFCache/tree/deadlock/SampleWeb

**Comment by moozzyk** [comment]
Thanks for sending the repro but it is well known that using `.Result` or `.Wait()` leads to deadlocks - these are blocking calls and once the task is finished it's trying to get back on the thread that is waiting for the task to finish. For cases like this the fix is to `await` the async method invocation instead of using `.Wait()`/`.Result` if the method the code is invoked from is `async`. If the method the code is invoked from is not `async` then use the sync counterpart. Having worked on the EF (I actually do remember this change by Andriy) and the ASP.Net team (SignalR) for 5+ years I don't recollect any legitimate case to call `.Result`/`.Wait()` in the user's code and [msdn](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/hh524395(v=vs.120)) makes it quite clear:

_The Result property is a blocking property. If you try to access it before its task is finished, the thread that's currently active is blocked until the task completes and the value is available. In most cases, you should access the value by using Await or await instead of accessing the property directly._

I will be more than happy to take your change if the deadlock happens when awaiting the call (AFAIR there were some corner cases in the ASP.Net framework where it actually used `.Result`/`.Wait()`) but I think taking it to make code that uses `.Result`/`.Wait()` code is just legitimizing a pattern that is discouraged (and potentially hurting the app itself).

**Comment by pjhuck** [comment]
Yes it is not best practice to use "sync over async", but there are times when it is hard to avoid, particularly when dealing with legacy code paths that are not "async all the way". Deadlocks are entirely avoidable, however, if the library code follows best practice and uses ConfigureAwait properly. (i'm not advocating for sync over async, as it also leads to other issues like thread pool starvation). And there are cases when you must use `.Result` or `Wait()` -- for an example a console app. 

It is a documented best practice to use `ConfigureAwait(false)` when writing library code. Deadlocks aside, it is also better for performance as you can avoid entering the synchronization context. This is important for GUI apps, so that the continuations don't run on the UI thread.  This article explains it better than I can: https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

> To summarize this third guideline, you should use Configure­Await when possible. Context-free code has better performance for GUI applications and is a useful technique for avoiding deadlocks when working with a partially async codebase. The exceptions to this guideline are methods that require the context.

This is the reason why EF itself uses `ConfigureAwaitI(false)` along with the core framework, and all other popular libraries. Here are some samples:
[Dapper](https://github.com/StackExchange/Dapper/blob/master/Dapper.Rainbow/Database.Async.cs#L29)
[Json.net](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonReader.Async.cs#L69)
[System.IO.BufferedStream](https://referencesource.microsoft.com/#mscorlib/system/io/bufferedstream.cs,353)

I realize that if possible applications shouldn't block on `.Result`, but as a library EFCache should respect best practices for async and do everything possible to avoid deadlocks.  There are no downsides to adding `ConfigureAwait(false)`

**Comment by moozzyk** [comment]
I played with your repro a bit yesterday and agree that it would be good to fix. I think the deadlock is happening because `.WithCurrentCulture()` is not actually invoked because all code is executed synchronously before it hits EFCache. Having said that - I am not sure if `.ConfigureAwait(false)` cuts it because it may result in losing the culture and I think it can break people.

**Comment by pjhuck** [comment]
Cool. Do you know why EF needs to flow the current culture? the commit I referenced above doesn't really explain why they do it. If the code which relies on the current culture is within EF, then I don't think EFCache needs to flow it, as it the current culture will be restored when control is returned to EF. But if the ado.net code needs the current culture for some reason, then EFCache would have to flow it. 

Let me know, I can port the `WithCurrentCulture()` awaiter in my PR. Unfortunately, it's internal, so I'll have to copy it.

**Comment by moozzyk** [comment]
Blast from the past: https://archive.codeplex.com/?p=entityframework and search for _Async implementation: ConfigureAwait(false) and non propagation of current culture and other execution context state_. 
I thought TaskExtensions is was public:

https://github.com/pjhuck/EFCache/blob/1568c59a57187bf4a1537251bd1b043933516eb3/SampleWeb/Controllers/HomeController.cs#L23

If it isn't due to the licensing I don't think I can accept just a copy of this file. I hate to say this but in the worst case this may require reinventing the wheel or ... reflection.

**Comment by pjhuck** [comment]
Thanks for the link. They mention they did so that  "user code" will get the correct culture

> This can cause exceptions coming from execution context not being correctly localized but potentially can cause other "ambient" values not being correct when executing user code.

In this case I don't see why EFCache needs to flow it. Whenever EF code is executing (and presumably it calls the user code), it will be running with the correct culture. 

With the ConfigureAwait()'s added to CachingCommand, the only code that is running without the correct culture is in CachingCommand. EF calls the command and awaits it, so by the time control is returned to EF, it's running again in the right culture. EFCache itself doesn't appear to care about the culture, so I don't think it needs to worry about it. 

As a side note, in .net 4.6 and later, the CurrentCulture is flowed regardless of `ConfigureAwait(false)` see https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?redirectedfrom=MSDN&view=netframework-4.8#culture-and-task-based-asynchronous-operations
However, this is not true for 4.5 and earlier so you probably don't want to rely on it. 

Anyway, let me know what you want to do.  Turns out `WithCurrentCulture()` is public so there is no need to copy it. The issue is that it wasn't added until EntityFramework 6.1.2, so EFCache would have to depend on that version instead of 6.1.0. Is that ok?

**Comment by moozzyk** [comment]
> As a side note, in .net 4.6 and later, the CurrentCulture is flowed regardless of ConfigureAwait(false) see https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?redirectedfrom=MSDN&view=netframework-4.8#culture-and-task-based-asynchronous-operations
However, this is not true for 4.5 and earlier so you probably don't want to rely on it.

Interesting! I stopped closely following .NET developments after I started working in a different environment and was not aware of this change. If I read the end support dates correctly, .NET Framework 4.5.2 mainstream support ended last year so I am not too concerned about a possible breaking change on versions below 4.6 (a workaround would be to stick with the current version of the package).

Thanks a lot for educating me!

**Comment by pjhuck** [comment]
thanks for accepting! Would it be possible to get a new release with the change?

**Comment by moozzyk** [comment]
Now that EF6 can work on Net Core I want to add support for this. I am
thinking about releasing both changes together. I would like to do this
rather soon.

**Comment by moozzyk** [comment]
@pjhuck - yesterday I uploaded a new version of the package containing your changes to NuGet
