### ISSUE TITLE
SingleOrDefault NotCached

### ISSUE THREAD

**Issue by icnocop** [moozzyk/EFCache#41]
Hi.

A call to `context.Set<T>().NotCached().SingleOrDefault();` doesn't seem to work as expected; it always seems to get data from the cache.

Is this a known issue?
Any ideas or work-arounds?

Thank you.

**Comment by moozzyk** [comment]
I would expect this to work if it doesn't it's probably a bug. Maybe you could try `context.Set<T>().Take(1).NotCached().SingleOrDefault()` - it's a bit gross but maybe it will work. You could also try excluding the entire EntitySet in the CachingPolicy but I don't know if this would fit for your scenario.

**Comment by icnocop** [comment]
Thank you for the quick reply and suggestions.

It works as expected if I exclude the EntitySet in the CachingPolicy, but I'm trying to avoid that.

Unfortunately, calling `context.Set<T>().Take(1).NotCached().SingleOrDefault()` as you suggested doesn't work either; it always seems to get data from the cache.

I also tried:

- `context.Set<T>().NotCached().Take(1).SingleOrDefault()`
- `context.Set<T>().Select(x => x).NotCached().SingleOrDefault()`
- `context.Set<T>().NotCached().Select(x => x).SingleOrDefault()`
- `context.Set<T>().NotCached().Where(x => true).SingleOrDefault()`
- `context.Set<T>().Where(x => true).NotCached().SingleOrDefault()`

Any other ideas?

Thank you.

**Comment by moozzyk** [comment]
I will have to debug - not sure what the issue can be here. In general .NotCached() should prevent caching.

**Comment by moozzyk** [comment]
So looks like this is completely busted and will not work. The `Single()` changes completely the generated query and I believe the `Cached()`/`NotCached()` won't work well if not attached at the end of the query. (I have a vague recollection of this being the case but it's been a while since I implemented this). The problem with `.Single()`/`First()` etc. is that they force evaluation instead of returning an `IQueryable<T>` so there is not a way (at least I don't know how to do this from the top of my head) to get the SQL query for the LINQ query and this is the main idea behind these extension methods. 

I found a workaround that is super gross but should work:
```
context.Set<T>().Take(1).NotCached().ToArray().SingleOrDefault()
```
I don't expect many people to understand how this works but basically `.ToArray()` forces evaluation making `NotCached()` to be effectively attached to the end of the query and forcing `.SingleOrDefault()` to be evaluated on the client side. On the server side the generated SQL queries look similar (queries are from the project tests):

**`Single()`**
```
SELECT TOP (2) \r\n    [c].[Id] AS [Id], \r\n    [c].[Name] AS [Name], \r\n    [c].[Flag] AS [Flag]\n    FROM [dbo].[Entities] AS [c]
```

 **`.Take(1).ToArray().SingleOrDefault()`**
```
SELECT TOP (1) \r\n    [c].[Id] AS [Id], \r\n    [c].[Name] AS [Name], \r\n    [c].[Flag] AS [Flag]\n    FROM [dbo].[Entities] AS [c]
```

The biggest problem is that the workaround is very obscure, non-idiomatic and on the verge of black magic. Someone will want to change it just to `.Single()` and it would be very hard to understand why things no longer work correctly.

**Comment by icnocop** [comment]
I'm wondering if we should add extension methods like `SingleOrDefaultNotCached()` to resolve this issue?

Thank you.

**Comment by moozzyk** [comment]
What I was trying to say above was that it is not possible to create an extension method like this. You don't have the point to intercept the query - so there is no place to hang the extension method of off. For methods that return `IQueryable<T>` it is easy because query generation is separated from query evaluation. `.Single()`, `.First()`, `Any()` etc. force evaluation and return the actual value so where would you put this method?

In fact there is one more workaround for this issue. If you get the generated SQL for your query you can register it as is in the registrar to override caching. Similarly to the issue above the first problem is to get this SQL.

**Comment by icnocop** [comment]
I created PR #44 to illustrate how I'm thinking we can resolve this issue.

Thank you.

**Comment by moozzyk** [comment]
Great! I didn't think of it that way. This definitely works and hides the ugliness!
