### ISSUE TITLE
InDatabaseCache : ICache

### ISSUE THREAD

**Issue by atrindade77** [moozzyk/EFCache#56]
Hi !

Thank you very much for this great package !

I'm trying to create an InDatabaseCache instead of InMemoryCache. We have 3 servers with LoadBalancing. So sometimes data was updated on Server1 but not invalidated on Server2. All these servers are on the same domain.

My idea is to implement an ICache that stores data on a database, so servers can share data between them without problem.

What do you think about that ? Is it a good idea ? Is this efficient ? And would you have any other solution ?

If you want, I can contribute to the project with this InDatabaseCache.

Thank you very much and have a nice day !

**Comment by moozzyk** [comment]
There are non-memory based implementations of ICache
- https://www.nuget.org/packages/DacheCache.Provider.EF/1.0.1-beta1
- https://www.nuget.org/packages/EFCache.RedisCache/
I don't know anything about your environment to answer any of your questions but I have doubts about using a database to avoid using database. Also, (relational) databases are better at storing and allowing to query data that has more structure rather than blobs.

The provider model should allow providing alternative implementations without coupling the implementation with this project. InMemoryCache is just a very simple and a bit crude implementation that could be used as a reference.
